# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='star_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Inicio'),
        ),
    ]
