# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180720_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='star_date',
            new_name='start_date',
        ),
    ]
