# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180723_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='decription',
            new_name='description',
        ),
    ]
