# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180810_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (2, 'Cancelado'), (1, 'Aprovado')], default=1, verbose_name='Situação'),
        ),
    ]
