# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20180810_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=1, verbose_name='Situação'),
        ),
    ]
