# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20180810_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprovado'), (2, 'Cancelado'), (0, 'Pendente')], default=1, verbose_name='Situação'),
        ),
    ]
