# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20180823_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancelado'), (0, 'Pendente'), (1, 'Aprovado')], default=1, verbose_name='Situação'),
        ),
    ]
