# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20180824_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (2, 'Cancelado'), (1, 'Aprovado')], default=1, verbose_name='Situação'),
        ),
    ]
