# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20180824_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Aprovado'), (0, 'Pendente'), (2, 'Cancelado')], default=1, verbose_name='Situação'),
        ),
    ]
