# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='tilte',
            new_name='title',
        ),
    ]
