# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
